- sign-off-checker/.helmignore
- sign-off-checker/Chart.yaml
- sign-off-checker/templates/NOTES.txt
- sign-off-checker/templates/_helpers.tpl
- sign-off-checker/templates/deployment.yaml
- sign-off-checker/templates/secrets.yaml
- sign-off-checker/templates/service.yaml
- sign-off-checker/values.yaml
The big majority of the code was generated by vscode helm extension
> sign-off-checker: initial chart version

- spark-api-jupyter/.helmignore
- spark-api-jupyter/Chart.yaml
- spark-api-jupyter/templates/NOTES.txt
- spark-api-jupyter/templates/_helpers.tpl
- spark-api-jupyter/templates/deployment.yaml
- spark-api-jupyter/templates/ingress.yaml
- spark-api-jupyter/templates/service.yaml
- spark-api-jupyter/values.yaml
still missing integration with babelfish
> first working version

- spark-api-jupyter/Chart.yaml
- spark-api-jupyter/templates/deployment.yaml
- spark-api-jupyter/values.yaml
This will be used from spark api container
bblfsh server has to mount an external disk with preloaded drivers. This is far from ideal, but current implementation does not load drivers and they have to be downloaded after server has started
> added bblfsh server container

- spark-api-jupyter/templates/deployment.yaml
- spark-api-jupyter/values.yaml
This is feasible since v0.0.6, hence we fix version
> Connect to bblfsh server from localhost

- kube-cert-manager/values.yaml
I'm not bumping the chart version as we're not using this anywhere for the moment.
> Default to an existing tag

- kube-cert-manager/templates/deployment.yaml
- kube-cert-manager/values.yaml
This goes more in-sync with our kube-lego chart
> explicti acmeUrl arg

- borges/Chart.yaml
- borges/templates/consumer-deployment.yaml
- borges/templates/producer-deployment.yaml
- borges/values.yaml
* Separate replica count per deployment
* quote env variables
* Add sysdig metrics
> Borges chart improvements

- borges/Chart.yaml
- borges/templates/consumer-deployment.yaml
- borges/values.yaml
This option deletes the temporary directory when it starts
> Add clean option to borges chart

- spark/README.md
- spark/templates/spark-worker-daemonset.yaml
- spark/values.yaml
This PR goes in hand with src-d/infrastructure#47
> Customize spark temporary files location

- spark/templates/spark-master-deployment.yaml
- spark/templates/spark-worker-daemonset.yaml
- spark/values.yaml
Add support for custom env variables
> add support for custom variables

- spark/templates/_helpers.tpl
- spark/templates/spark-worker-deployment.yaml
- spark/values.yaml
* Make temp dir unique per release
* Make sure that two pods of a deployment don't land in
the same node
cc @r0mainK
> transformed into a deployment

- scylla/.helmignore
- scylla/Chart.yaml
- scylla/templates/_helpers.tpl
- scylla/templates/scylla-configmap.yaml
- scylla/templates/scylla-service.yaml
- scylla/templates/scylla-statefulset.yaml
- scylla/values.yaml
Aims at deploying easily a scylla database, in order to work with apollo on k8 cluster.
> Added scylla chart

- rovers/.helmignore
- rovers/Chart.yaml
- rovers/README.md
- rovers/templates/_helpers.tpl
- rovers/templates/deployment.yaml
- rovers/templates/initdb-job.yaml
- rovers/templates/secret.yaml
- rovers/values.yaml
> Added rovers chart

- bblfsh-dashboard/Chart.yaml
- bblfsh-dashboard/values.yaml
And set everything to latest by default
> Added drivers

- bblfsh-dashboard/values.yaml
This was missing from https://github.com/src-d/charts/pull/42
> dashboard version to latest

- borges/Chart.yaml
- borges/README.md
- borges/templates/consumer-deployment.yaml
- borges/templates/producer-deployment.yaml
- borges/values.yaml
* Now mentions producer is started with:
borges producer mentions
* Added support to change log format to json (default)
* Updated parameter `--mentionsqueue` to `--mentions-queue`
> Update borges helm chart with new producer syntax and log format

- borges/Chart.yaml
- borges/templates/consumer-deployment.yaml
- borges/templates/producer-deployment.yaml
- borges/values.yaml
> Moved to src-d/go-log env vars to configure debug

- borges/Chart.yaml
- borges/templates/consumer-deployment.yaml
- borges/templates/producer-deployment.yaml
- borges/values.yaml
> added fluentbit parser annotation

- gitbase-playground/.helmignore
- gitbase-playground/Chart.yaml
- gitbase-playground/README.md
- gitbase-playground/templates/NOTES.txt
- gitbase-playground/templates/_helpers.tpl
- gitbase-playground/templates/clone-git-repositories-configmap.yaml
- gitbase-playground/templates/deployment.yaml
- gitbase-playground/templates/ingress.yaml
- gitbase-playground/templates/install-bblfshd-drivers-configmap.yaml
- gitbase-playground/templates/service.yaml
- gitbase-playground/templates/statefulset.yaml
- gitbase-playground/values.yaml
See `README.md` for some details on how the chart works.
> New gitbase-playground chart

- spark/Chart.yaml
- spark/values.yaml
Up to a version that supports spark executors properly
> upgrade webui proxy

- spark/Chart.yaml
- spark/templates/spark-webui-proxy-deployment.yaml
> fix prefix to use release namespace

- gitbase-playground/Chart.yaml
- gitbase-playground/templates/deployment.yaml
- gitbase-playground/values.yaml
Signed-off-by: Maxim Sukharev <maxim@sourced.tech>
> Add footer HTML env var to gitbase playground

- gitbase-playground/Chart.yaml
- gitbase-playground/templates/statefulset.yaml
Typo spotted in https://github.com/src-d/charts/pull/59
> Fix typo for squashEnable

- lookout/.helmignore
- lookout/Chart.yaml
- lookout/templates/_helpers.tpl
- lookout/templates/dummy-analyzer-deployment.yaml
- lookout/templates/dummy-analyzer-service.yaml
- lookout/templates/lookout-configmap.yaml
- lookout/templates/lookout-deployment.yaml
- lookout/templates/lookout-init-db.yaml
- lookout/templates/lookout-service.yaml
- lookout/templates/secret.yaml
- lookout/values.yaml
> lookout chart

- lookout/Chart.yaml
- lookout/templates/lookout-deployment.yaml
This was missing from https://github.com/src-d/charts/pull/63
cc @bzz
> upgrade deployment on configmap

- lookout/templates/lookout-configmap.yaml
> added repositories config section

- lookout-style-analyzer/.helmignore
- lookout-style-analyzer/Chart.yaml
- lookout-style-analyzer/templates/_helpers.tpl
- lookout-style-analyzer/templates/deployment.yaml
- lookout-style-analyzer/templates/init-db.yaml
- lookout-style-analyzer/templates/pvc.yaml
- lookout-style-analyzer/templates/service.yaml
- lookout-style-analyzer/values.yaml
> Lookout style analyzer chart

- lookout-style-analyzer/values.yaml
> fix values example

- rovers/Chart.yaml
- rovers/values.yaml
> move images to docker hub

- kube-cert-manager/Chart.yaml
- kube-cert-manager/values.yaml
> images to docker hub

- lookout/Chart.yaml
- lookout/templates/lookout-deployment.yaml
- lookout/values.yaml
Part of https://github.com/src-d/lookout/issues/229
> remove repos as positional argument

- gitbase-web/Chart.yaml
- gitbase-web/values.yaml
> Change pullPolicy to always on bblfshd in gitbase-web

- lookout/Chart.yaml
- lookout/templates/lookout-deployment.yaml
> Add ability to load GitHub app key file in lookout

- lookout-gometalint-analyzer/.helmignore
- lookout-gometalint-analyzer/Chart.yaml
- lookout-gometalint-analyzer/templates/_helpers.tpl
- lookout-gometalint-analyzer/templates/deployment.yaml
- lookout-gometalint-analyzer/templates/service.yaml
- lookout-gometalint-analyzer/values.yaml
> added lookout gometalint analyzer

- lookout-gometalint-analyzer/templates/deployment.yaml
> used a 1.5 compatible api version

- lookout/Chart.yaml
- lookout/templates/lookout-deployment.yaml
>  Parse an absolute path in .Values.providers.github.private_key

- lookout/Chart.yaml
- lookout/templates/lookout-deployment.yaml
> Add subPath for config.yml in lookout

- lookout/Chart.yaml
- lookout/templates/lookout-deployment.yaml
> Fix mount paths in lookout

- lookout-sonarcheck-analyzer/.helmignore
- lookout-sonarcheck-analyzer/Chart.yaml
- lookout-sonarcheck-analyzer/README.md
- lookout-sonarcheck-analyzer/templates/_helpers.tpl
- lookout-sonarcheck-analyzer/templates/deployment.yaml
- lookout-sonarcheck-analyzer/templates/service.yaml
- lookout-sonarcheck-analyzer/values.yaml
> added lookout-sonarcheck-analyzer

- gitbase-web/Chart.yaml
- gitbase-web/templates/clone-git-repositories-configmap.yaml
- gitbase-web/values.yaml
> Install Git in clone-git-repositories.sh

- bblfsh-web/Chart.yaml
- bblfsh-web/templates/deployment-using-external-bblfshd-server.yaml
- bblfsh-web/templates/deployment-with-sidecar-bblfshd-container.yaml
- bblfsh-web/values.yaml
> added node selector

- drone/Chart.yaml
- drone/templates/deployment-agent.yaml
- drone/templates/deployment-server.yaml
- drone/values.yaml
> added node selector to drone

- online-net-stock-alert/.helmignore
- online-net-stock-alert/Chart.yaml
- online-net-stock-alert/templates/_helpers.tpl
- online-net-stock-alert/templates/cronjob.yaml
- online-net-stock-alert/values.yaml
> Add chart for online-net-stock-alert

- lookout-style-analyzer/templates/deployment.yaml
- lookout-style-analyzer/templates/init-db.yaml
- lookout-style-analyzer/values.yaml
- lookout/templates/lookout-deployment.yaml
- lookout/templates/lookout-init-db.yaml
- lookout/values.yaml
> Prepare lookout chart to work with Cloud SQL

- lookout/Chart.yaml
> Release lookout Chart 0.5.0

- lookout/Chart.yaml
- lookout/templates/lookout-deployment.yaml
> Add missing {{end}}

- website-redirect/.helmignore
- website-redirect/Chart.yaml
- website-redirect/templates/_helpers.tpl
- website-redirect/templates/caddy-configmap.yaml
- website-redirect/templates/deployment.yaml
- website-redirect/templates/ingress.yaml
- website-redirect/templates/service.yaml
- website-redirect/values.yaml
> Add website-redirect chart to set up a redirect of a sunseted website

- website-redirect/Chart.yaml
- website-redirect/templates/caddy-configmap.yaml
- website-redirect/templates/deployment.yaml
GCE does not do tcp probes and doesn't like redirects
> Another healthcheck approach

- website-redirect/Chart.yaml
- website-redirect/values.yaml
> service type to NodePort (needed by GCE ingress)

- lookout/Chart.yaml
- lookout/templates/work-service.yaml
> Fixed service selector

- gitbase-web/Chart.yaml
- gitbase-web/templates/deployment.yaml
- gitbase-web/values.yaml
> Warn if bblfshdServer or gitbaseServer is set and not both are present

- kubernetes-local-pv-provisioner/.helmignore
- kubernetes-local-pv-provisioner/Chart.yaml
- kubernetes-local-pv-provisioner/templates/_helpers.tpl
- kubernetes-local-pv-provisioner/templates/daemonset.yaml
- kubernetes-local-pv-provisioner/templates/rbac.yaml
- kubernetes-local-pv-provisioner/templates/serviceaccount.yaml
- kubernetes-local-pv-provisioner/values.yaml
> Add chart for kubernetes-local-pv-provisioner

- bblfshd/Chart.yaml
- bblfshd/templates/deployment.yaml
- bblfshd/values.yaml
Signed-off-by: David Riosalido <driosalido@sourced.tech>
> Added Affinity section to Chart

- jupyter-single/Chart.yaml
- jupyter-single/templates/pvc.yaml
> Add name to the PVC of jupyter-single

- bblfshd/Chart.yaml
- bblfshd/values.yaml
Do not merge until https://github.com/bblfsh/csharp-driver/issues/13 is fixed
> added csharp driver

- bblfshd/Chart.yaml
- bblfshd/values.yaml
> Update the default version of bblfshd

- bblfshd-sidecar/Chart.yaml
- bblfshd-sidecar/values.yaml
> Add csharp to the bblfsh sidecar chart

- scylla/Chart.yaml
- scylla/templates/scylla-statefulset.yaml
- scylla/values.yaml
> Added ability to use PVC to Scylla

- gemini/.helmignore
- gemini/Chart.yaml
- gemini/templates/_helpers.tpl
- gemini/templates/deployment.yaml
- gemini/values.yaml
> Add gemini chart

- spark/Chart.yaml
- spark/templates/spark-master-deployment.yaml
- spark/templates/spark-worker-deployment.yaml
- spark/values.yaml
> Replace alpha affinity with new notation

- scylla/Chart.yaml
- scylla/templates/scylla-statefulset.yaml
> Fix indentation

- scylla/Chart.yaml
- scylla/templates/scylla-statefulset.yaml
> Fix metadata.name

- spark/Chart.yaml
- spark/templates/spark-worker-deployment.yaml
> Add ability to define custom volumes in spark workers

- scylla/Chart.yaml
- scylla/templates/scylla-config-configmap.yaml
- scylla/templates/scylla-statefulset.yaml
- scylla/values.yaml
> Add a configmap for scylla config

- gitbase/Chart.yaml
- gitbase/templates/statefulset.yaml
- gitbase/values.yaml
> Add extraEnv to Gitbase

- scylla/Chart.yaml
- scylla/templates/scylla-config-configmap.yaml
- scylla/values.yaml
Signed-off-by: David Riosalido <driosalido@sourced.tech>
> Changed scylla write timeout

- spark/Chart.yaml
- spark/templates/spark-master-deployment.yaml
- spark/values.yaml
> Support custom volumes on the Spark Master

- hue/.helmignore
- hue/Chart.yaml
- hue/templates/NOTES.txt
- hue/templates/_helpers.tpl
- hue/templates/configmap.yaml
- hue/templates/deployment.yaml
- hue/templates/ingress.yaml
- hue/templates/service.yaml
- hue/values.yaml
> Add Hue chart

- lookout/Chart.yaml
- lookout/templates/lookout-init-db.yaml
So it also deletes failed jobs
> fix hook delete policy

- jupyter-single/Chart.yaml
- jupyter-single/templates/deployment.yaml
- jupyter-single/values.yaml
This adds the ability to override the image command for custom configuration options (some are only supported as start command)
> Add ability to add a custom command to Jupyter-single

- jupyter-single/Chart.yaml
- jupyter-single/templates/deployment.yaml
- jupyter-single/values.yaml
> Add support for a custom service account in Jupyter

- gitbase/Chart.yaml
- gitbase/templates/statefulset.yaml
- gitbase/values.yaml
> Add support to add a custom volume as repo storage

- gitbase-web/Chart.yaml
- gitbase-web/templates/service.yaml
- gitbase-web/values.yaml
> Support setting a nodeport on gitbase-web

- borges/Chart.yaml
- borges/templates/consumer-deployment.yaml
- borges/templates/producer-deployment.yaml
- borges/templates/republish-deployment.yaml
> use new fluentbit.io/parser to specify a parser

- lookout-style-analyzer/Chart.yaml
- lookout-style-analyzer/templates/deployment.yaml
> fix args order

- lookout/Chart.yaml
- lookout/templates/lookout-configmap.yaml
- lookout/values.yaml
> Add timeout section to config

- spark/Chart.yaml
- spark/templates/spark-webui-proxy-deployment.yaml
- spark/values.yaml
> Allow to change service type and nodeport for SparkWebUIProxy

- prometheus-external-monitor/.helmignore
- prometheus-external-monitor/Chart.yaml
- prometheus-external-monitor/templates/_helpers.tpl
- prometheus-external-monitor/templates/service.yaml
- prometheus-external-monitor/templates/servicemonitor.yaml
- prometheus-external-monitor/values.yaml
> Add a chart that configures endpoints for external monitoring

- hue/Chart.yaml
- hue/templates/configmap.yaml
- hue/values.yaml
> Add blacklist_apps option

- spark/Chart.yaml
- spark/templates/configmap.yaml
> Fix the configmap definition

- hue/Chart.yaml
- hue/templates/configmap.yaml
- hue/values.yaml
To avoid error msgs to components not in use.
> Removed the unneeded configs

- hue/templates/configmap.yaml
> booleans need to be converted for string functions to work

- hue/Chart.yaml
- hue/templates/deployment.yaml
> added checksum to reload if configmap changes

- hue/Chart.yaml
- hue/templates/configmap.yaml
> fix nice name in template

- google-cloud-dns-healthcheck/.helmignore
- google-cloud-dns-healthcheck/Chart.yaml
- google-cloud-dns-healthcheck/templates/_helpers.tpl
- google-cloud-dns-healthcheck/templates/cronjob.yaml
- google-cloud-dns-healthcheck/values.yaml
> Created google-cloud-dns-healthcheck chart

- lookout-typo-analyzer/.helmignore
- lookout-typo-analyzer/Chart.yaml
- lookout-typo-analyzer/templates/_helpers.tpl
- lookout-typo-analyzer/templates/deployment.yaml
- lookout-typo-analyzer/templates/service.yaml
- lookout-typo-analyzer/values.yaml
This adds a chart for the typos part of style-analyzer, it has sightly different needs than the formatting analyzer part.
> Add lookout-typo-analyzer chart

- google-cloud-dns-healthcheck/Chart.yaml
- google-cloud-dns-healthcheck/values.yaml
To use one that actually exists
> Fixed default image tag

- hue/Chart.yaml
- hue/templates/configmap.yaml
> Fixed typo in rdbms definition

- nfs-gluster-bridge/.helmignore
- nfs-gluster-bridge/Chart.yaml
- nfs-gluster-bridge/templates/NOTES.txt
- nfs-gluster-bridge/templates/_helpers.tpl
- nfs-gluster-bridge/templates/deployment.yaml
- nfs-gluster-bridge/templates/service.yaml
- nfs-gluster-bridge/values.yaml
> added nfs-gluster-bridge chart

- gitbase/Chart.yaml
- gitbase/templates/statefulset.yaml
- gitbase/values.yaml
> Added pod management policy setting

- gitbase/Chart.yaml
- gitbase/templates/service.yaml
- gitbase/values.yaml
> Add the possibility of making the service headless

- drone/Chart.yaml
> Added missing api version to drone chart

- spark/Chart.yaml
> Added missing apiVersion

- ghost-gcs-backup/.helmignore
- ghost-gcs-backup/Chart.yaml
- ghost-gcs-backup/templates/_helpers.tpl
- ghost-gcs-backup/templates/cronjob.yaml
- ghost-gcs-backup/templates/secret.yaml
- ghost-gcs-backup/values.yaml
> Add ghost-gcs-backup

- bblfshd/Chart.yaml
- bblfshd/values.yaml
All in title, just updating to last release
Signed-off-by: Romain Keramitas <r.keramitas@gmail.com>
> Update bblfshd chart value

- hue/Chart.yaml
- hue/templates/configmap.yaml
- hue/values.yaml
Added HUE search config in order to be able to create dashboards.
Signed-off-by: David Riosalido <driosalido@sourced.tech>
> Added search config to HUE

- spark/Chart.yaml
- spark/templates/spark-worker-deployment.yaml
- spark/values.yaml
> change additionalPodContainers in the correct case

- ghost-gcs-backup/Chart.yaml
- ghost-gcs-backup/templates/cronjob.yaml
- ghost-gcs-backup/values.yaml
> Added missing GCS_BUCKET env variable

- ghost-gcs-backup/ci/test-values.yaml
> added test value for gcs chart

- spark/Chart.yaml
- spark/templates/livy-service.yaml
Service label component in livy wasn't updated
> Fix livy service template

- spark/Chart.yaml
- spark/templates/livy-service.yaml
- spark/templates/spark-master-deployment.yaml
The WebUI port were wrongly assigned to the livy port.
> Fix spark ports

- spark/Chart.yaml
- spark/templates/spark-webui-proxy-service.yaml
> A variable was left unchanged in the refactor

- spark/Chart.yaml
- spark/templates/spark-worker-deployment.yaml
> Fix typo in worker extra env

- thrift/Chart.yaml
- thrift/values.yaml
imagePullSecrets is an array not an object
> Small fixes in Thrift chart

- spark-thrift-server/Chart.yaml
- spark-thrift-server/templates/deployment.yaml
> Quote bblfshPort

- spark-thrift-server/Chart.yaml
- spark-thrift-server/templates/deployment.yaml
> Fix incorrect variable for imagePullSecrets

- sourced-ui/Chart.yaml
- sourced-ui/templates/service.yaml
- sourced-ui/values.yaml
> Add NodePort support to sourced-ui

- spark-thrift-server/Chart.yaml
- spark-thrift-server/templates/deployment.yaml
> Correct jar path

- spark-thrift-server/Chart.yaml
- spark-thrift-server/templates/deployment.yaml
- spark-thrift-server/values.yaml
> Add configurable probes to spark-thrift-server

- spark-thrift-server/Chart.yaml
- spark-thrift-server/templates/_helpers.tpl
- spark-thrift-server/templates/deployment.yaml
- spark-thrift-server/templates/gitbase-secret.yaml
- spark-thrift-server/values.yaml
> Add Gitbase user and password to spark-thrift-server

- spark-thrift-server/Chart.yaml
- spark-thrift-server/templates/deployment.yaml
- spark-thrift-server/values.yaml
> Correct port used by spark-thrift-server

- spark-thrift-server/Chart.yaml
- spark-thrift-server/templates/deployment.yaml
> Set spark.driver.host to pod IP in thrift-server

- spark-thrift-server/Chart.yaml
- spark-thrift-server/templates/deployment.yaml
The environmental variables do not work properly.
> Pass gitbase and bblfsh conf in command args

- sourced-ui/Chart.yaml
- sourced-ui/templates/init-db-job.yaml
> Remove required values from initdb job

- ct-install.yaml
- infra/k8s-pod-headless-service-operator/.helmignore
- infra/k8s-pod-headless-service-operator/Chart.yaml
- infra/k8s-pod-headless-service-operator/templates/_helpers.tpl
- infra/k8s-pod-headless-service-operator/templates/deployment.yaml
- infra/k8s-pod-headless-service-operator/templates/rbac.yaml
- infra/k8s-pod-headless-service-operator/templates/serviceaccount.yaml
- infra/k8s-pod-headless-service-operator/values.yaml
> Add k8s-pod-headless-service-operator chart

- CONTRIBUTING.md
- DCO
- README.md
> Add a proper readme, contributing and DCO

- ct-install.yaml
- stable/bblfsh-web/Chart.yaml
- stable/bblfsh-web/ci/test-values.yaml
- stable/bblfsh-web/templates/tests/test-configmap.yaml
- stable/bblfsh-web/templates/tests/test.yaml
> added tests for bblfsh-web chart

- stable/bblfshd-sidecar/Chart.yaml
- stable/bblfshd-sidecar/templates/_helpers.tpl
- stable/bblfshd-sidecar/templates/install-drivers-configmap.yaml
- stable/bblfshd-sidecar/values.yaml
This sets the new default of driver.install and comes by default with a -drivers image of bblfshd
> Make the install drivers postStart optionionall in bblfshd-sidecar

- ct-install.yaml
- stable/gitbase/Chart.yaml
- stable/gitbase/ci/test-values.yaml
- stable/gitbase/templates/tests/test-configmap.yaml
- stable/gitbase/templates/tests/test.yaml
> Added tests to gitbase chart

- stable/bblfshd/Chart.yaml
- stable/bblfshd/templates/deployment.yaml
> Use checksum only when installing drivers

- stable/sourced-ui/Chart.yaml
- stable/sourced-ui/templates/deployment.yaml
- stable/sourced-ui/templates/warmup-configmap.yaml
> Add a post lifecycle hook to warmup the workers in sourced-ui

- stable/sourced-ui/Chart.yaml
- stable/sourced-ui/templates/init-db-job.yaml
- stable/sourced-ui/values.yaml
> Make the chart work with sourced-ui 0.3.0

- stable/bblfshd-sidecar/Chart.yaml
- stable/bblfshd-sidecar/templates/_helpers.tpl
- stable/bblfshd-sidecar/templates/service.yaml
- stable/bblfshd-sidecar/templates/servicemonitor.yaml
- stable/bblfshd-sidecar/values.yaml
> Add metrics to bblfshd-sidecar

- stable/bblfshd-sidecar/Chart.yaml
- stable/bblfshd-sidecar/templates/service.yaml
A non valid yaml is created otherwise
> Render additionalServiceMatchLabels if they exist

- infra/prometheus-external-monitor/Chart.yaml
- infra/prometheus-external-monitor/templates/servicemonitor.yaml
- infra/prometheus-external-monitor/values.yaml
> Add basicAuth support to prometheus-external-monitor

- infra/prometheus-external-monitor/Chart.yaml
- infra/prometheus-external-monitor/templates/servicemonitor.yaml
- infra/prometheus-external-monitor/values.yaml
> Add scheme option to endpoints

- stable/sourced-ui/Chart.yaml
- stable/sourced-ui/templates/admin-secret.yaml
- stable/sourced-ui/templates/deployment.yaml
- stable/sourced-ui/templates/gitbase-secret.yaml
- stable/sourced-ui/templates/init-db-job.yaml
- stable/sourced-ui/templates/postgres-secret.yaml
> give the possibility of setting secret keys

- ct-install.yaml
- infra/landing/.helmignore
- infra/landing/Chart.yaml
- infra/landing/README.md
- infra/landing/ci/test-values.yaml
- infra/landing/templates/_helpers.tpl
- infra/landing/templates/deployment.yaml
- infra/landing/templates/ingress.yaml
- infra/landing/templates/service.yaml
- infra/landing/values.yaml
> Move the landing chart to the charts repo

- ct-install.yaml
- infra/code-annotation/.helmignore
- infra/code-annotation/Chart.yaml
- infra/code-annotation/README.md
- infra/code-annotation/ci/test-values.yaml
- infra/code-annotation/templates/_helpers.tpl
- infra/code-annotation/templates/deployment.yaml
- infra/code-annotation/templates/ingress.yaml
- infra/code-annotation/templates/persistent-volume-claim.yaml
- infra/code-annotation/templates/secrets.yaml
- infra/code-annotation/templates/service.yaml
- infra/code-annotation/values.yaml
This was copied from code-annotation repo as part
of the CD migration to Travis.
The only changes have been cosmetic to make the linter
tests pass
> Added code-annotation chart

- ct-install.yaml
- infra/ml-deployment/.helmignore
- infra/ml-deployment/Chart.yaml
- infra/ml-deployment/templates/NOTES.txt
- infra/ml-deployment/templates/_helpers.tpl
- infra/ml-deployment/templates/deployment.yaml
- infra/ml-deployment/templates/service.yaml
- infra/ml-deployment/values.yaml
This chart will be used to deploy typical ml
apps in their cluster
> Added ml-deployment chart

- infra/ml-deployment/Chart.yaml
- infra/ml-deployment/templates/deployment.yaml
> Added env var with the pod name
