src-d/charts

spark/README.md, spark/templates/spark-worker-daemonset.yaml, spark/values.yaml
This will enable the possibility to colocate bblfsh containers in the same pod as we have spark workers so that we access them locally
Config hasn't been set as an array of hashes as it is not possible to pass that kind of structure with `--set` option
=> Now we can pass additional containers to worker pod

tiller/.helmignore, tiller/Chart.yaml, tiller/README.md, tiller/templates/tiller-svc-deployment.yaml
This is meant to be used by terraform helm provider that currently does
not support tiller installation
=> add tiller helm chart

drone/Chart.yaml, drone/templates/deployment-agent.yaml, drone/templates/deployment-server.yaml
If present, upgrades won't work when changing the chart version.
Kubernetes discourages making label selector updates because the new selector does not select ReplicaSets or Pods created with the old selector, resulting in orphaning all old ReplicaSets and Pods and creating new ones (see https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#label-selector-updates)
=> drone: remove chart version from deployment's labels

kube-cert-manager/.helmignore, kube-cert-manager/Chart.yaml, kube-cert-manager/README.md, kube-cert-manager/templates/_helpers.tpl, kube-cert-manager/templates/certificate-type.yaml, kube-cert-manager/templates/deployment.yaml, kube-cert-manager/templates/google-key-secret.yaml, kube-cert-manager/templates/persistent-volume-claim.yaml, kube-cert-manager/values.yaml
Running in development cluster with image `quay.io/srcd/kube-cert-manager:v0.5.0-srcd-1` built from our [kube-cert-manager fork](https://github.com/src-d/kube-cert-manager) running
=> Kube certs manager chart

borges/Chart.yaml, borges/templates/consumer-deployment.yaml, borges/templates/producer-deployment.yaml, borges/values.yaml
This parameter must be provided when deploying the chart.
=> Make image.tag required in borges chart

bblfsh-dashboard/Chart.yaml, bblfsh-dashboard/templates/deployment-using-external-bblfshd-server.yaml, bblfsh-dashboard/templates/deployment-with-sidecar-bblfshd-container.yaml, bblfsh-dashboard/templates/install-bblfshd-drivers-configmap.yaml, bblfsh-dashboard/templates/service.yaml, bblfsh-dashboard/values.yaml
Separated the deployments with/without server in two files to make it clearer.
Drivers are installed from a list rather than using --all or --recommended as that would open the possibility of having different version of the drivers in the different pods of the deployment
=> Moved to bblfshd from bblfsh-server

spark/Chart.yaml, spark/templates/spark-master-deployment.yaml, spark/templates/spark-webui-proxy-deployment.yaml, spark/templates/spark-worker-daemonset.yaml
If not, it prevents helm from upgrading pods when chart's version is bumped.
=> Spark: remove chart version from pod's metadata

spark/Chart.yaml, spark/templates/_helpers.tpl
This also fixes a bug where we could not use "spark" as release name as it was setting the `SPARK_MASTER_PORT` variable (which is used internally by spark init scripts)
```
$ helm install spark --name=spark
NAME:   spark
LAST DEPLOYED: Mon Mar 12 14:12:47 2018
NAMESPACE: default
STATUS: DEPLOYED
RESOURCES:
==> v1/Service
NAME                     CLUSTER-IP      EXTERNAL-IP  PORT(S)   AGE
spark-spark-webui        10.99.103.187   <none>       8080/TCP  0s
spark-spark-master       10.107.183.164  <none>       7077/TCP  0s
spark-spark-webui-proxy  10.106.201.248  <none>       80/TCP    0s
==> v1beta1/Deployment
NAME                     DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
spark-spark-master       1        1        1           0          0s
spark-spark-worker       1        1        1 …
```
=> moved to standard helm naming convention

scylla/Chart.yaml, scylla/templates/scylla-statefulset.yaml
I added the node selector, the node defaults to `master-3` but can be set otherwise, and a volume can now be mounted for the scylla data instead of memory
=> Add node selector and Volume

bblfsh-dashboard/Chart.yaml, bblfsh-dashboard/templates/deployment-using-external-bblfshd-server.yaml, bblfsh-dashboard/templates/deployment-with-sidecar-bblfshd-container.yaml, bblfsh-dashboard/templates/install-bblfshd-drivers-configmap.yaml, bblfsh-dashboard/values.yaml
caused by https://github.com/bblfsh/dashboard/pull/122/
required by https://github.com/src-d/issues-infrastructure/issues/150#issuecomment-387961280
Since https://github.com/bblfsh/dashboard/pull/122/ the `dashboard` will communicate with `bblfshd` using the tcp control network to retrieve the list of installed drivers. To do so, it is needed:
- `dashboard` backend needs to know what is the address of the tcp control network &rarr; [here](https://github.com/src-d/charts/pull/44/files#diff-259a96fa622cb6e771f1a7c3e82e577dR33),
- `bblfshd` needs to expose the control network using `tcp` under `9433` port &rarr; [here](https://github.com/src-d/charts/pull/44/files#diff-259a96fa622cb6e771f1a7c3e82e577dR40),
- `bblfshd` drivers needs to be installed using the new tcp control network &rarr; …
=> Use the tcp network for control protocol

gitbase-playground/Chart.yaml, gitbase-playground/templates/statefulset.yaml, gitbase-playground/values.yaml
=> Add GITBASE_READONLY env var

borges/Chart.yaml, borges/README.md, borges/values.yaml
We've changed the docker registry for borges from `quay.io` to Docker hub in the latest release `0.17.0`.
=> Update borges chart to use docker hub images

lookout/Chart.yaml, lookout/templates/dummy-analyzer-deployment.yaml, lookout/templates/lookout-deployment.yaml, lookout/values.yaml
Part of https://github.com/src-d/lookout/issues/180.
Depends on https://github.com/src-d/lookout/pull/252.
=> Add http health probes to lookout

lookout/Chart.yaml, lookout/templates/dummy-analyzer-deployment.yaml, lookout/templates/lookout-deployment.yaml, lookout/values.yaml
In PR #72 I mixed address with port, and now [the deployments fail](https://drone.srcd.host/src-d/lookout/175) with:
```
Error: UPGRADE FAILED: Deployment.extensions "lookout-dummy-analyzer" is invalid: [spec.template.spec.containers[0].livenessProbe.httpGet.port: Invalid value: "0.0.0.0:8091": must contain only alpha-numeric characters (a-z, 0-9), and hyphens (-), spec.template.spec.containers[0].livenessProbe.httpGet.port: Invalid value: "0.0.0.0:8091": must contain at least one letter or number (a-z, 0-9), spec.template.spec.containers[0].readinessProbe.httpGet.port: Invalid value: "0.0.0.0:8091": must contain only alpha-numeric characters (a-z, 0-9), and hyphens (-), spec.template.spec.containers[0].readinessProbe.httpGet.port: Invalid value: "0.0.0.0:8091": must contain at least one …
```
=> Fix lookout probes ports

lookout/Chart.yaml, lookout/templates/lookout-deployment.yaml
Latest lookout deployment failed (https://drone.srcd.host/src-d/lookout/215), apparently the changes in https://github.com/src-d/charts/pull/79 use `Values` instead of `.Values`.
=> Fix lookout chart syntax

lookout-style-analyzer/Chart.yaml, lookout-style-analyzer/templates/init-db.yaml, lookout/Chart.yaml, lookout/templates/lookout-init-db.yaml
Kubernetes wants in a job for all it's containers to end. With the use of sidecar containers like needed for Cloud SQL this becomes an issue. 
There is a Kubernetes issue for this: https://github.com/kubernetes/kubernetes/issues/25908
=> Fix job Cloud SQL

.travis.yml
Travis deployment option for GitHub pages: `keep-history: Optional, create incremental commit instead of doing push force, defaults to false.`
=> Keep history of old charts on GH Pages

gitbase-web/Chart.yaml, gitbase-web/values.yaml
- Change default service type from NodePort to ClusterIP, which is the
default ServiceType in Kubernetes.
- Change default port from 8080 to 80 which, being the standard, is more
intuitive. There is no point in using 8080 when we have a dedicated
virtual IP.
Signed-off-by: Santiago M. Mola <santi@mola.io>
=> [Do not merge][gitbase-web] use ClusterIP on port 80 by default

bblfsh-web/templates/deployment.yaml
These were missing thus the service which had the more labels in the selector could not find the deployment
=> Add missing labels to bblfsh-web deployment

gitbase-web/Chart.yaml, gitbase-web/templates/deployment.yaml, gitbase-web/values.yaml
- Renamed gitbaseServer.address to gitbaseServer.host
- Added comments to values.yaml with usage examples.
Only host (no host:port) is expected on gitbaseServer.host. This was
previously not clear.
Signed-off-by: Santiago M. Mola <santi@mola.io>
=> [gitbase-web] use gitbaseServer.host instead of .address

bblfsh-web/Chart.yaml, bblfsh-web/templates/deployment.yaml, bblfsh-web/templates/service.yaml, bblfsh-web/values.yaml
- Use ClusterIP by default.
- Move to service.port/internalPort, for consistency with gitbase-web.
Also closer to official charts.
Signed-off-by: Santiago M. Mola <santi@mola.io>
=> [bblfsh-web] use ClusterIP by default

gitbase-web/Chart.yaml, gitbase-web/templates/ingress.yaml, gitbase-web/values.yaml
- Change ingress.yaml to match latest Helm (2.11.0) template as much as
possible.
- This allows setting multiple hosts and does not assume a particular
ingress controller.
Signed-off-by: Santiago M. Mola <santi@mola.io>
=> [gitbase-web] use default ingress template (Helm 2.11.0)

bblfsh-web/Chart.yaml, bblfsh-web/templates/deployment.yaml, bblfsh-web/values.yaml
The idea is to have the web services pods running on different pods as suggested by @rporres in [src-d/infrastructure#201] (https://github.com/src-d/infrastructure/issues/201)
First idea is to use a default value to enable/disable the location constraint.
```
antiAffinityEnabled: true
```
Tested in development with bblfsh-web and working as expected. With just one node in the cluster the second pod is not deployed as one of them is already deployed in the node. 
If a second node is added to the cluster, both pods are allocated one in each node.
=> AntiAffinityRules for bblsfsh-web

spark/Chart.yaml, spark/README.md, spark/templates/spark-webui-proxy-deployment.yaml, spark/values.yaml
It can now be enabled via `WebUiProxy.ReverseProxy.ApiPrefix`
This is a breaking change... But it makes much more sense to make it this way...
=> Remove api-proxy by default

prometheus-external-monitor/Chart.yaml, prometheus-external-monitor/templates/endpoint.yaml, prometheus-external-monitor/templates/service.yaml, prometheus-external-monitor/values.yaml
ExternalName Service is not enough to get scrapped, and endpoint is also needed. 
Also the full hostname is resolved to the public address and the node-exporter is only listening in the internal, so I've added the IP to the set of values that has to be provided in the values.
=> Added endpoints

website-redirect/Chart.yaml, website-redirect/templates/caddy-configmap.yaml, website-redirect/templates/ingress.yaml, website-redirect/values.yaml
This is a breaking change for the website-redirect chart that allows for multiple
entries in one install of the chart.
redirects accepts multiple entries in an array that configure the server
to serve multiple virtual hosts with different redirects.
This as well sets up the ingress (with TLS) for all entered hostnames.
=> Refactor website redirect chart to support multiple entries

.travis.yml, scripts/repo-sync.sh
This should fix the repo-sync step by excluding the docs folder.
It also patches the Travis file to only do the sync after the charts got tested
=> Fix repo sync

ghost-gcs-backup/ci/test-values.yaml, ghost-gcs-backup/templates/cronjob.yaml, ghost-gcs-backup/values.yaml
* Added test values to make chart install
* Fixed linting issues
* Removed value key from ghost api key as it was already managed
through a secret and it was making tests fail
=> Fix linting and test issues in ghost backup chart

spark/Chart.yaml, spark/templates/spark-master-deployment.yaml, spark/templates/spark-master-service.yaml, spark/values.yaml
Changes needed to run spark 2.3.2 
* The service needs to be headless
Since master dynamically creates dedicated RPC port for each worker
you won't be able to route workers to master.
* The spark.driver.host parameter is auto set to the pod hostname.
This variable is created by the spark context and sent to the workers.
The workers tries to talk back with the master using this address
so we need to have this hostname being resolved by the DNS.
* The host and port parameter are set via ENV Variables
=> Fix spark 233

sourced-ui/Chart.yaml, sourced-ui/templates/deployment.yaml, sourced-ui/templates/gitbase-secret.yaml, sourced-ui/values.yaml
Making this optional is needed for deployment with a Spark SQL backend.
If a username and password are specified the Spark SQL backend will fail to
connect as there is no LDAP authentication configured.
=> Make gitbase username/password optional in sourced-ui

stable/spark-thrift-server/Chart.yaml, stable/spark-thrift-server/templates/deployment.yaml, stable/spark-thrift-server/values.yaml
Allow to set `spark.executor.cores` and `spark.cores.max`
=> Make thrift server aware of core limits

ct-install.yaml, stable/spark/Chart.yaml, stable/spark/templates/tests/test-job-pod.yaml, stable/spark/templates/tests/test-webui-configmap.yaml, stable/spark/templates/tests/test-webui.yaml
This adds 2 tests to the Spark chart.
1 will launch a test job to see if the setup works
The other will test the web ui and the liveness reported
=> Add tests to Spark chart

ct-install.yaml, stable/bblfshd/Chart.yaml, stable/bblfshd/ci/test-values.yaml, stable/bblfshd/templates/tests/test-configmap.yaml, stable/bblfshd/templates/tests/test.yaml
Tests have been written in Python using bblfsh python client as we
don't have a bblfsh cli yet that we can download easily for these tests
(see bblfsh/go-client#115)
=> added tests to bblfshd chart

stable/bblfshd-sidecar/Chart.yaml, stable/bblfshd-sidecar/templates/_helpers.tpl
Since helpers are included in the parent chart we need to use a
workarround to access the values
=> Fix Values in helper of bblfshd-sidecar

.travis.yml, scripts/install-minikube.sh
This checks if the charts that need to be installed are changed on the test step.
Only then it will set up Minikube, this will save several minutes on releasing charts that do not have tests (yet)
=> Only install minikube if charts are changed

scripts/install-minikube.sh
Fixes issues like https://travis-ci.com/src-d/charts/jobs/212989113#L284 on branch builds
=> Fix issues with TRAVIS_COMMIT_RANGE on branch

stable/bblfshd/Chart.yaml, stable/bblfshd/ci/test-values.yaml, stable/bblfshd/templates/NOTES.txt, stable/bblfshd/templates/_helpers.tpl, stable/bblfshd/templates/deployment.yaml, stable/bblfshd/templates/install-drivers-configmap.yaml, stable/bblfshd/templates/service.yaml, stable/bblfshd/templates/servicemonitor.yaml, stable/bblfshd/templates/tests/test-configmap.yaml, stable/bblfshd/templates/tests/test.yaml, stable/bblfshd/values.yaml
This updates the bblfshd chart to the latest Helm and Kubernetes standards,
It is a breaking change as it will rename the resources differently when the
chart name is equal to the release name.
=> Improve the bblfshd chart

stable/bblfsh-web/Chart.yaml, stable/bblfsh-web/values.yaml, stable/bblfshd/Chart.yaml
The GKE ingress controller sees / as only the root, changed it to /*
=> Fix default ingress path

infra/website-redirect/Chart.yaml, infra/website-redirect/values.yaml
Caddy 1.0.3 contains a fix for a HTTP/2 DoS
=> Use Caddy 1.0.3
